### ISSUE TITLE
[Enhancement] Add contribution.md file

### ISSUE THREAD

**Issue by Cibiyanna26** [yesahem/Medium-Blog#13]
As medium-blog is an open-source project, by creating a contribution.md file will really help new contributors to understand the need of project and guidelines.

I am a contributor from HacktoberFest I would like to contribute to this project. it would be great if you assign this issue to me.

**Comment by yesahem** [comment]
Go ahead @Cibiyanna26

**Comment by Cibiyanna26** [comment]
Thanks @yesahem
