### ISSUE TITLE
Legacy Major Change

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#15]
Willing to Shift the whole codebase form React+Workers to NextJs

Since NextJS is a full stack framework it will help us making this SEO friendly and will give many abstraction under the hood

**Comment by geekyharsh05** [comment]
@yesahem Makes a lot of sense, but i will suggest it is better to use hono for back-end because it is already deployed and works on the edge & React is always there for the front-end.

**Comment by yesahem** [comment]
This makes sense more than mine !
Thanks @geekyharsh05 ✨
