### ISSUE TITLE
Add DarkMode to the sites

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#16]
Since there is no toggle button for dark mode add a button for dark mode toggle

**Comment by cxy012** [comment]
Hello,
I am a contributor from HacktoberFest and I’m excited about contributing to this project. I noticed that the issue [#16] is marked with the `hacktoberfest` label, and I would love to help out by working on this.
Could you please assign this issue to me so I can start working on it?

**Comment by yesahem** [comment]
Sure go ahead but don't forgot to follow the way of  contributions to this repo 

Please read the README.md file once

**Comment by HackesticMedusa** [comment]
Please assign me to this issue, I’d like to add a dark mode toggle button.

**Comment by yesahem** [comment]
Who ever solves the issue and made the PR first will be auto assigned to the issue

**Comment by vaishvi2811** [comment]
Hi, can I work on this? Please assign

**Comment by yesahem** [comment]
solved !!!
