### ISSUE TITLE
feat: use modular approach in hono.js

### ISSUE THREAD

**Issue by geekyharsh05** [yesahem/Medium-Blog#21]
### Setup in backend:
- [x] Controllers
- [x] Middlewares
- [x] Routes
- [x] Added Delete Blog Route

### Setup in frontend:
- [x] Solved Frontend Blog Creation Issue
- [x] Added View Blog Page Component

Overall resulting in improving the code structure.

@yesahem Can you please add it under hacktoberfest label.

**Comment by yesahem** [comment]
Can you please attach some screenshot what actually you want to say in this issue?? @geekyharsh05

**Comment by geekyharsh05** [comment]
Like this: 
<img width="404" alt="Screenshot 2024-10-06 at 12 39 28 AM" src="https://github.com/user-attachments/assets/282d15aa-1057-4748-a7d2-6266a35821ca">

**Comment by yesahem** [comment]
Ahh I see 
Did you checked that weather that folder structure is supported in mono or not?

BTW if you want to do it go ahead @geekyharsh05

**Comment by geekyharsh05** [comment]
> Ahh I see 
> Did you checked that weather that folder structure is supported in mono or not?
> 
> BTW if you want to do it go ahead @geekyharsh05 

Yeah hono.js follows factory patterns.
Refer to this: [Click Me](https://hono.dev/docs/helpers/factory)

**Comment by yesahem** [comment]
go ahead @geekyharsh05

**Comment by yesahem** [comment]
any update @geekyharsh05

**Comment by geekyharsh05** [comment]
@yesahem I was busy with something else, will make a pr in the next 48 hrs.

**Comment by yesahem** [comment]
Okay do not make pr in hurry take your time !

**Comment by geekyharsh05** [comment]
@yesahem Yeah i will keep that in mind.

**Comment by geekyharsh05** [comment]
@yesahem Done with the user controller and route setup.
Now working on the blog controller.

<img width="1440" alt="Screenshot 2024-10-09 at 3 58 08 PM" src="https://github.com/user-attachments/assets/fc4c921d-1174-413c-be82-4a26ca545095">


<img width="1440" alt="Screenshot 2024-10-09 at 4 16 30 PM" src="https://github.com/user-attachments/assets/754c7bd2-3598-4211-a6da-9f33c1a58944">

<img width="1440" alt="Screenshot 2024-10-09 at 4 16 52 PM" src="https://github.com/user-attachments/assets/974f1afc-c37e-4bf8-9d91-8e9b6a64f83c">

**Comment by geekyharsh05** [comment]
@yesahem  One more question, Why are you not using zod schema directly from the package that you have on the npm registry.
It is a bad practice like if we want to infer a particular type of schema we should use that in frontend, and use the schema thing in the backend. Following the `DRY Principle`.
We should import it directly from the package that you have created?

<img width="839" alt="Screenshot 2024-10-09 at 4 21 54 PM" src="https://github.com/user-attachments/assets/7ae503ae-2019-48ef-a566-8e4eeb9cb202">

**Comment by geekyharsh05** [comment]
@yesahem And more thing i forgot to mention we should hash the password for the user? Can i do that?

<img width="985" alt="Screenshot 2024-10-09 at 4 28 00 PM" src="https://github.com/user-attachments/assets/de0d930b-30b5-4215-8383-5911fbe5984e">

**Comment by yesahem** [comment]
> @yesahem And more thing i forgot to mention we should hash the password for the user? Can i do that?
> 
> <img width="985" alt="Screenshot 2024-10-09 at 4 28 00 PM" src="https://github.com/user-attachments/assets/de0d930b-30b5-4215-8383-5911fbe5984e">
> 

Issue is created already and the pr is made but need some improvement in the pr 

Go through the pr made the changes 
And please try to create a seperate pr for hashing the password addressing the issue number 

Best of luck..

**Comment by geekyharsh05** [comment]
@yesahem Yeah I will keep that in mind as the project structure will change I will do that in another pr.

**Comment by geekyharsh05** [comment]
@yesahem What about the zod schema package thing? Shouldn't we directly import the schema from it?

**Comment by geekyharsh05** [comment]
@yesahem For now i am doing this way after that you can update it on your side.

**Comment by geekyharsh05** [comment]
@yesahem The blog post is getting created in frontend also.

<img width="1440" alt="Screenshot 2024-10-09 at 6 31 47 PM" src="https://github.com/user-attachments/assets/b208e939-1e45-47bb-a092-da7cff1d3a25">


<img width="1434" alt="Screenshot 2024-10-09 at 6 32 50 PM" src="https://github.com/user-attachments/assets/a811a580-e519-4e64-9d3d-06cdd276b43c">

**Comment by yesahem** [comment]
Looks good @geekyharsh05

**Comment by geekyharsh05** [comment]
@yesahem I have solved the upload blog issue

**Comment by geekyharsh05** [comment]
@yesahem 
### Creating a blog
<img width="1440" alt="Screenshot 2024-10-09 at 9 14 27 PM" src="https://github.com/user-attachments/assets/3cabfd7b-f3f0-4e32-bc38-909445127f29">

### Blog Created
<img width="1440" alt="Screenshot 2024-10-09 at 9 15 00 PM" src="https://github.com/user-attachments/assets/a7bff579-b19a-447c-bbcb-bc45c83f1215">

### View Blog Page

<img width="1440" alt="Screenshot 2024-10-09 at 9 15 21 PM" src="https://github.com/user-attachments/assets/c147109f-c086-4c7c-8542-0b28377681e3">

### A full fledged dummy blog
<img width="1440" alt="Screenshot 2024-10-09 at 9 15 33 PM" src="https://github.com/user-attachments/assets/97405dc4-3f45-4075-a03a-064e6d85d3e6">

**Comment by geekyharsh05** [comment]
@yesahem Making a pr soon.

**Comment by yesahem** [comment]
Looks awesome @geekyharsh05

**Comment by geekyharsh05** [comment]
@yesahem thanks

**Comment by yesahem** [comment]
Go ahead @geekyharsh05
