### ISSUE TITLE
feat: use React Hook Form & Tanstack Query

### ISSUE THREAD

**Issue by geekyharsh05** [yesahem/Medium-Blog#28]
1. **Efficient State Management**: React Hook Form simplifies form handling with minimal re-renders, while TanStack Query streamlines data fetching, enhancing performance and user experience.

2. **Improved Validation and Asynchronous Operations**: Integrating both libraries allows for seamless form validation and easier management of asynchronous data, resulting in a more responsive and user-friendly application.

@yesahem I have just created this issue for the open source contributors who are keen to contribute. If someone does not takes it. Then at then end of this month i will solve it.

**Comment by yesahem** [comment]
okay sure @geekyharsh05

**Comment by shanksxz** [comment]
Hi @yesahem , I'd love to take on this issue and contribute to integrating React Hook Form and TanStack Query. Could you please assign it to me? Also, if possible, could you add the Hacktoberfest label to it? Thanks!

**Comment by yesahem** [comment]
go ahead !!

**Comment by shanksxz** [comment]
@geekyharsh05 can you take a look at pr?

**Comment by yesahem** [comment]
Thanks for contribution @shanksxz ✨
Happy Coding !!!
