### ISSUE TITLE
feat: add update blog functionality in frontend.

### ISSUE THREAD

**Issue by geekyharsh05** [yesahem/Medium-Blog#30]
Users should be able to either update the title or the content of the blog.

**Comment by Ameerjafar** [comment]
@yesahem can you assign me this issue

**Comment by Ameerjafar** [comment]
@geekyharsh05 title only is enough or should i change the both title and content

**Comment by geekyharsh05** [comment]
@Ameerjafar You have to change both. Imagine a scenario where there an author wants to only edit the title of that post or there is the same scenario here he wants to only edit the content of the post.
