### ISSUE TITLE
feat: add Delete blog functionality in frontend 

### ISSUE THREAD

**Issue by geekyharsh05** [yesahem/Medium-Blog#31]
Users should be able to delete the blog.

**Comment by shanksxz** [comment]
@yesahem , I'd love to take on this issue.

**Comment by yesahem** [comment]
What is the status @shanksxz ??

**Comment by shanksxz** [comment]
> What is the status @shanksxz ??

?

**Comment by Ameerjafar** [comment]
@geekyharsh05 can you assign me this issue.
