### ISSUE TITLE
Improve UI for Theme Toggle: Use Icon Instead of Text

### ISSUE THREAD

**Issue by shanksxz** [yesahem/Medium-Blog#34]
Currently, the theme toggle is displayed as text ("Dark Mode"). To enhance the user experience and make the UI more intuitive, I suggest replacing the "Dark Mode" text with a theme icon (e.g., a sun/moon). This will make it visually cleaner and more in line with modern design practices.

![image](https://github.com/user-attachments/assets/bcc7da9b-5c61-4d6e-88c5-14547493c6c1)

**Comment by yesahem** [comment]
Do you wish to do it or should I assign it someone else @shanksxz ?

**Comment by shanksxz** [comment]
I would love to take this on! Please assign it to me. Thanks!

**Comment by shanksxz** [comment]
This is how it's looking now:
![image](https://github.com/user-attachments/assets/a64fd986-b232-4105-9421-1317a7c8776b)
![image](https://github.com/user-attachments/assets/6b2aaea3-27e2-43a4-a8de-92287b3ccc18)

Can I improve the UI of the nav a little bit?

**Comment by yesahem** [comment]
Change the ui as much as you want but try to keep it minimal

**Comment by shanksxz** [comment]
How about this?
![image](https://github.com/user-attachments/assets/9092b9c2-42cb-4bcc-9602-b95853afbdb1)

**Comment by yesahem** [comment]
I Guess its just change in font right?

**Comment by shanksxz** [comment]
Yes, I changed the font style from bold to normal and also improved the alignment. Should I create a pull request for these changes, or do you have any other suggestions for the UI?

**Comment by yesahem** [comment]
I don't have any suggestions in mind but I don't think just for the font changes you have to make a separate PR "just only for font changes" !!!

Sorry @shanksxz

**Comment by shanksxz** [comment]
i guess originally the issue was regarding using an icon instead of "Dark mode" or "light mode".
also, check if this look good to you?
![image](https://github.com/user-attachments/assets/2e675cec-8817-461b-a4eb-9072febc401a)

**Comment by yesahem** [comment]
> i guess originally the issue was regarding using an icon instead of "Dark mode" or "light mode".
> also, check if this look good to you?
> ![image](https://github.com/user-attachments/assets/2e675cec-8817-461b-a4eb-9072febc401a)
> 

Currently teavelling will be able to review it tommorow or day after tommorow..

Btw thanks for the pr but a small change please shift the theme toggle button to the left of home route means on the left side of the routing links (optional feature requested)

**Comment by shanksxz** [comment]
yeah, no problem.
like this?
![image](https://github.com/user-attachments/assets/ea91c138-5f90-45e5-ad91-306913a8fdfa)
