### ISSUE TITLE
Add password Hashing in signup and signin

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#5]
Hash user's password before sending request to db 

similarly compare the users given password with the hash from the db and if hash matches the login else popup wrong password

**Comment by himanshuranjan007** [comment]
i am willing to work on this issue to create the password hashing , can you please assign it to me . Thanks!

**Comment by yesahem** [comment]
Sure, go ahead @himanshuranjan007

**Comment by yesahem** [comment]
any update @himanshuranjan007

**Comment by pantharshit007** [comment]
@yesahem it seems to me the user @himanshuranjan007  is not available should I work on this issue?

**Comment by geekyharsh05** [comment]
@pandeyashu08 Can you please look into this?

**Comment by pandeyashu08** [comment]
@geekyharsh05 yeah sure
