### ISSUE TITLE
Re-Design and Develop Login and Signup page with responsive layout

### ISSUE THREAD

**Issue by Abhii5496** [yesahem/Medium-Blog#51]
![image](https://github.com/user-attachments/assets/4527514f-76eb-4c44-b941-54a31077aa83)
![image](https://github.com/user-attachments/assets/6dc27d77-ebe1-455c-81bb-0cc668cb2bd4)

Current login and signup page is ugly and not responsive on different screen sizes , which makes user experience bad.
i would like to work on it under hacktoberfest2024 , can you assign me ?

**Comment by yesahem** [comment]
@geekyharsh05

**Comment by Abhii5496** [comment]
![image](https://github.com/user-attachments/assets/e176e3de-5a7a-4331-a9a2-235552a7af8f)
![image](https://github.com/user-attachments/assets/fd0517ac-6e7c-4e7b-ae7c-78a8d6bdc4cb)
![image](https://github.com/user-attachments/assets/0f4b6070-affa-4a6c-80af-7d20a3ed0f3b)
![image](https://github.com/user-attachments/assets/504496a3-fa16-4397-b29e-4d22e955639c)
@yesahem check it , i have developed it already .

**Comment by yesahem** [comment]
add the photos in light mode also and create a pr @Abhii5496 
looks cool to me !!
