### ISSUE TITLE
user is not able to view blog after hitting the website url (if user shares the URL )

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#56]
for reference

![Screenshot 2024-10-19 at 2 23 17 PM](https://github.com/user-attachments/assets/e5080b07-5243-4822-a4ea-96b9e6beee2a)

**Comment by shanksxz** [comment]
@yesahem , the view-blog route is protected. We will need to remove the auth middleware for the /get route in the backend to allow access. If you want, you can assign the issue to me.

**Comment by yesahem** [comment]
bro it is solved 
Forgot to mention and the issue will be merged to production within 2 3 days 

abhi busy hu mai 


Sorry for that but also also thanks for the update 
Happy coding ✨

**Comment by shanksxz** [comment]
@yesahem no problem!
