### ISSUE TITLE
User is able to edit or delete any blogs 

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#57]
while viewinig the all user post anyone can delete anyone's blog even if the post doesn't belongs to them!!!!!

Thats not right

**Comment by shanksxz** [comment]
@yesahem, I'd love to work on the issue.

**Comment by yesahem** [comment]
Go ahead ✨️✨️

**Comment by shanksxz** [comment]
@yesahem assign?

**Comment by Ameerjafar** [comment]
I have made the mistake when added the update and delete functionality 😔😔😔@yesahem can I raise pr for this one. If @shanksxz did not do that?

**Comment by yesahem** [comment]
Ask @shanksxz

**Comment by pantharshit007** [comment]
hey @yesahem can i do that since both of them haven't done that I already found the mistakes.
